name: Clear GitHub Dependency Graph
on:
  workflow_dispatch:
    inputs:
      jobCorrelator:
        required: true
        type: string
  
permissions: write-all

jobs:
  clear-graph:
    runs-on: ubuntu-latest
    steps:
#     - uses: gradle/gradle-build-action/actions/clear-dependency-graph@dependency-graph
#       with:
#         job-correlator: ${{ inputs.jobCorrelator }}
    - name: Set current timestamp as env variable
      run: echo "NOW=$(date -Iseconds)" >> $GITHUB_ENV
    - name: Submit empty dependency graph
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.ACFGP_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/bigdaz/test-dependency-graph/dependency-graph/snapshots \
        -d '{ "version" : 0, "job" : { "id" : "${{ github.run_id }}", "correlator" : "${{ inputs.jobCorrelator }} " }, "sha" : "ffb66dd7b41dd42ffef3b5f1c2a9b388b737f6e6", "ref" : "refs/heads/main",  "detector" : { "name" : "GitHub Dependency Graph Gradle Plugin", "version" : "0.0.3", "url" : "https://github.com/gradle/github-dependency-graph-gradle-plugin" }, "manifests" : {}, "scanned" : "${{ env.NOW }}" }'
    - run: echo "::notice ::Cleared dependency graph for job correlator '${{ inputs.jobCorrelator }}'"
