name: Composite action dependency graph

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  composite-generate-and-submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bigdaz/test-dependency-graph-2/.github/actions/dependency-submission@main
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - uses: bigdaz/test-dependency-graph-2/.github/actions/dependency-submission@main
      with:
        gradle-version: 8.6-rc-1
        build-root-directory: extra-build-1
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
