name: Composite action dependency graph

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  composite-generate-and-submit-dependency-graph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dummy: ['one', 'two']
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/gradle-build-action/actions/dependency-submission@dd/dependency-submission-action
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    - uses: gradle/gradle-build-action/actions/dependency-submission@dd/dependency-submission-action
      with:
        gradle-version: 8.6-rc-1
        build-root-directory: extra-build-1
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
