name: dependency-graph
on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Generate dependency graph
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
         upload-dependency-graph: true
    - name: Report dependency graph
      run: cat build/reports/github-dependency-report/github-dependency-manifest.json 
    - name: Save dependency graph
      uses: actions/upload-artifact@v3
      with:
        name: dependency-graph
        path: build/reports/github-dependency-report/github-dependency-manifest.json
        retention-days: 1
