name: dependency-graph
on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Generate dependency graph and save artifact
      uses: gradle/gradle-build-action/actions/generate-dependency-graph@dd/dependency-graph
