name: dependency-graph
on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Generate dependency graph and save artifact
      uses: gradle/gradle-build-action/actions/generate-dependency-graph@dd/dependency-graph
