name: dependency-graph-upload
on:
  workflow_run:
    workflows: ["dependency-graph"]
    types:
      - completed

permissions:
  contents: write

jobs:
  upload-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve dependency graph
      uses: actions/download-artifact@v3
      with:
        name: dependency-graph
        path: github-dependency-report
    - name: Report dependency graph
      run: |
        ls -la github-dependency-report
        cat github-dependency-report/github-dependency-manifest.json 
    - name: Upload dependency graph
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/bigdaz/test-dependency-graph/dependency-graph/snapshots -d @github-dependency-report/github-dependency-manifest.json
        
  

