name: dependency-graph-upload
on:
  workflow_run:
    workflows: ["dependency-graph"]
    types:
      - completed

permissions: write-all

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Submit dependency graph
      uses: ./.github/actions/submit-dependency-graph
