name: dependency-graph-upload
on:
  workflow_run:
    workflows: ["dependency-graph"]
    types:
      - completed

permissions: write-all

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: gradle/gradle-build-action/actions/submit-dependency-graph@dd/dependency-graph
