name: dependency-graph
on:
  workflow_dispatch:
  push:

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Generate dependency graph
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
         upload-dependency-graph: true
    - name: Report dependency graph
      run: cat build/reports/github-dependency-report/github-dependency-manifest.json          
    - name: Upload dependency graph
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/bigdaz/test-dependency-graph/dependency-graph/snapshots -d @build/reports/github-dependency-report/github-dependency-manifest.json
        
  

