name: generate-dependency-graph
on:
  workflow_dispatch:
  # pull_request:

permissions: {}

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ["assemble", "test"]
        version: [1, 2]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@dd/dependency-review-support
      with:
        cache-disabled: true
        dependency-graph: generate
    - name: Run ${{ matrix.task }} build ${{ matrix.version }}
      run: ./gradlew ${{ matrix.task }}

