name: generate-and-submit-dependency-graph
on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@dd/dependency-graph-actions    
    - name: Generate dependency graph for main build
      uses: gradle/gradle-build-action/actions/dependency-graph-generate@dd/dependency-graph-actions
#     - name: Generate dependency graph for extra-build-1
#       uses: gradle/gradle-build-action/actions/dependency-graph-generate@dd/dependency-graph-actions
#       with:
#         build-root-directory: extra-build-1
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action/actions/dependency-graph-submit@dd/dependency-graph-actions
