name: generate-and-submit-dependency-graph
on:
  workflow_dispatch:
  pull_request:
  
permissions: write-all

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
        dependency-graph: generate
    - name: Run main build
      run: ./gradlew build
    - name: Generate dependency graph for extra-build-1
      run: ./gradlew build
      working-directory: extra-build-1

  generate-graph-help:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true
        dependency-graph: generate
        args: help

  submit-graph:
    runs-on: ubuntu-latest
    needs: [generate-graph, generate-graph-help]
    steps:
    - name: Retrieve dependency graph artifacts and submit
      uses: gradle/gradle-build-action@dd/dependency-review-support
      with:
        cache-disabled: true
        dependency-graph: download-and-submit
    - name: Dependency review
      uses: actions/dependency-review-action@v3
