name: generate-and-submit-dependency-graph
on:
  workflow_dispatch:

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@dd/dependency-graph-actions    
    - name: Generate dependency graph and save artifact
      uses: gradle/gradle-build-action/actions/dependency-graph-generate@dd/dependency-graph-actions
    - name: Display structure before downloaded files
      run: ls -R        
    - name: Download dependency graph artifact
      uses: actions/download-artifact@v3
      with:
        name: dependency-graph
    - name: Display structure after downloaded files
      run: ls -R        
  submit-graph:
    runs-on: ubuntu-latest
    needs: generate-graph
    steps:
    - name: Download dependency graph artifact
      uses: actions/download-artifact@v3
      with:
        name: dependency-graph
    - name: Display structure of downloaded files
      run: ls -R        
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action/actions/dependency-graph-submit@dd/dependency-graph-actions
