name: generate-and-submit-dependency-graph
on:
  workflow_dispatch:
  push:
  pull_request:
  
permissions: write-all

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
        cache-disabled: true
    - name: list init scripts
      run: ls -la /home/runner/.gradle/init.d
    - name: Run main build
      run: ./gradlew :GitHubDependencyGraphPlugin_generateDependencyGraph
    - name: Generate dependency graph for extra-build-1
      run: ./gradlew :GitHubDependencyGraphPlugin_generateDependencyGraph
      working-directory: extra-build-1
  submit-graph:
    runs-on: ubuntu-latest
    needs: generate-graph
    steps:
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action/actions/dependency-graph-submit@dd/dependency-graph
