name: generate-and-submit-dependency-graph
on:
  pull_request:
  
permissions:
  contents: write
  # Note that this permission will not be available if the PR is from a forked repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/gradle-build-action@dd/dependency-review-support
      with:
        dependency-graph: generate-and-submit
    - name: Run a build and generate the dependency graph which will be submitted post-job
      run: ./gradlew build

  dependency-review:
    needs: build
    runs-on: ubuntu-latest
    - name: Perform dependency review
      uses: actions/dependency-review-action@v3on:
