name: submit-dependency-graph
on:
  workflow_run:
    workflows: ["generate-dependency-graph"]
    types:
      - completed

permissions: write-all

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action@dd/dependency-graph
      with:
        dependency-graph: download-and-submit
  on-generation-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "::warning::Dependency graph generation failed"
