name: submit-dependency-graph
on:
  workflow_run:
    workflows: ["generate-dependency-graph"]
    types:
      - completed

permissions: write-all

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump workflow_run context
      env:
        WORKFLOW_RUN_CONTEXT: ${{ toJSON(github.event.workflow_run) }}
      run: echo "$WORKFLOW_RUN_CONTEXT"
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action@dd/artifact-lib-update
      with:
        dependency-graph: download-and-submit
    - name: Dependency review
      uses: actions/dependency-review-action@v3
      with:
        base-ref: main
        head-ref: ${{ github.event.workflow_run.head_branch }}
  on-generation-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "::warning::Dependency graph generation failed"
